services:
  # Blue app container
  app_blue:
    image: ${DOCKER_IMAGE}
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"

  # Green app container
  app_green:
    image: ${DOCKER_IMAGE}
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"

  # Nginx reverse proxy container
  nginx:
    image: nginx:stable
    ports:
      - "${NGINX_HOST_PORT}:${PORT}"
      - "80:${PORT}"
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL} 
